store/cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"
urlpatterns = [

    path('',views.cart_details,name='cart_details'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),
    path('fullremove/<int:product_id>/', views.full_remove, name='fullremove'),


    ]

store/search_app/urls.py
from django.urls import path

from search_app import views

app_name = "search_app"
urlpatterns = [

    path('',views.SearchResult,name='SearchResult'),
    ]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include("storeapp.urls")),
    path('search/',include("search_app.urls")),
    path('cart/',include("cart.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/storeapp/urls.py
from django.urls import path

from storeapp import views

app_name = "storeapp"
urlpatterns = [

    path('',views.AllProdCat,name='AllProdCat'),
    path('<slug:c_slug>/',views.AllProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.prodDetails, name='prodDetails'),
]

store/cart/models.py
from django.db import models
from storeapp.models import Products
# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}' .format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}' .format(self.product)

store/search_app/models.py
from django.db import models

# Create your models here.

store/storeapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class category (models.Model):
    name=models.CharField(max_length=255,unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering=('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}' .format(self.name)

    def get_url(self):
        return reverse('storeapp:products_by_category',args=[self.slug])
class Products(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    image = models.ImageField(upload_to='category')
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(category,on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}' .format(self.name)

    def get_url(self):
        return reverse('storeapp:prodDetails',args=[self.category.slug, self.slug])

store/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . models import CartItem,Cart
from storeapp.models import Products
from django.core.exceptions import  ObjectDoesNotExist

# Create your views here.
def test(request):
    return render(request,"test.html")

def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return  cart

def add_cart(request,product_id):
    product = Products.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = cart_id(request))

        cart.save()

    try:
        cart_item = CartItem.objects.get(product = product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:

            cart_item.quantity +=1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product = product,cart=cart,quantity=1)
        cart_item.save()
    return redirect('cart:cart_details')

def cart_details(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Products,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)

    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details')

store/search_app/views.py
from django.shortcuts import render

# Create your views here.
from storeapp.models import Products
from django.db.models import Q


def SearchResult(request):
    products=None
    query=None
    if request.method == "POST":

        query=request.POST['searched']
        products=Products.objects.all().filter(Q(name__contains = query) | Q(description__contains = query))

    return  render(request,'search.html',{'query':query,'products': products})

store/storeapp/views.py
from django.shortcuts import render, get_object_or_404
from . models import category,Products
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.

def test(request):

    return render(request,'index.html')

def AllProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_page = get_object_or_404(category,slug=c_slug)
        products_list=Products.objects.all().filter(category=c_page,available= True)
    else:
        products_list=Products.objects.all().filter(available = True)

    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
            products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products': products})

def prodDetails(request,c_slug,product_slug):
    try:
        product=Products.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title%} {% endblock %} </title>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock content %}

</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %} " ></script>
</body>
</html>

store/templates/cart.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}
    Welcome to your Cart.Review your items and continue to buy
{% endblock %}
{% block title %}
        Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center"> <br>
        <h1> Your Cart Empty</h1> <br>
        <p class="text-center"> To continue shopping please click <a href="{% url 'storeapp:AllProdCat' %}"> here</a> </p>

    </div>
</div>

{% else %}
    <div>
        <div class="text-center"><br>
            <h1 class="text-center my_title">Your Shopping Cart</h1> <br>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table my_title">

                <thead class="my_custom_thead my_title">
                <tr>
                    <th colspan="5">Your items</th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}


                   <tr>
                    <td><a href="cart_item.product.get_absolute_url"> <img src="{{ cart_item.product.image.url}}" alt="" width="100px" height="100px" class="float-leftrounded custom_image"> </a> </td>
                    <td class="my_prod_title">{{ cart_item.product.name }} <br>
                        SKU:{{cart_item.product.id}}<br>
                        Price:{{cart_item.product.price}} <br>
                        Qty:{{cart_item.quantity}} <br>

                    </td>
                    <td> ${{cart_item.sub_total}}</td>
                    <td> {{cart_item.subtotal}}</td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td> &nbsp; <a href="{% url 'cart:add_cart' cart_item.product.id %}"  class="custom_a"> <img src="{% static 'img/add_icon.png' %} " width="15px" height="15px" class="custom_icon">&nbsp;</a>
                          &nbsp;  <a href="{% url 'cart:remove' cart_item.product_id %}" class="custom_a"> <img src="{% static 'img/minus_icon.png' %} " width="15px" height="15px" class="custom_icon"></a>
                          &nbsp;  <a href="{% url 'cart:fullremove' cart_item.product_id %}" class="custom_a"> <img src="{% static 'img/delete_icon.png' %} " width="15px" height="15px" class="custom_icon"> </a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart:remove' cart_item.product_id %}" class="custom_a"> <img src="{% static 'img/minus_icon.png' %} " width="15px" height="15px" class="custom_icon"></a>
                        &nbsp;<a href="{% url 'cart:fullremove' cart_item.product_id %}" class="custom_a"> <img src="{% static 'img/delete_icon.png' %} " width="15px" height="15px" class="custom_icon"> </a>
                    </td>
                    {% endif %}

                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table my_title">
                <thead class="my_custom_thead my_title" >
                <tr>
                    <th>
                        CheckOut
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="text-left">Your Total is <strong>{{total}}</strong></td>
                    </tr>
                 <tr>   <td>Please review your items before proceding with payment</td>
                </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'storeapp:AllProdCat' %}" class="btn btn_secondary btn_block my_custom_button">Continue Shopping</a>
            </div>
        </div>
    </div>

{% endif %}

{% endblock %}

store/templates/category.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}
    {% if category %}
        {{ category.description | truncatewords:155 }}
    {% else %}
        Welcome to XYZ Supermarket
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        XYZ Supermarket
    {% endif %}
{% endblock %}
{% block content %}
{% if category %}
    <div class="container">
        <div class="row my_row_class" >
            <div class="mx-auto">
                <p> <a href="{% url 'storeapp:AllProdCat' %}">Our Product Collection</a> </p>
            </div>

        </div>
    </div>
    {% endif %}
    <div class="mx_auto">
        {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">

    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify"> {{category.description}} </p>
    </div>
    {% else %}
    <div>
        <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" width="1335px" height="250px" alt="Our Product">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title" > <b>Our Products Collections </b></h1>
        <p class="text-justify my_desc">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>
    </div>
    {% endif %}
    <div class="container">
        <div class="row card-group">
            {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="min-width:10rem">
                    <a href="{{product.get_url}}"> <img class="card-img-top my_image img_category" src="{{product.image.url}}" alt="{{product.name}}"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
                </div>
            </div>
            {% endfor %}
        </div>


        <br>
        <div class="text-center">
        {%if products.has_previous %} {# whether the previous page exists #}
            <a href="?page={{products.previous_page_number}}"><</a> {# link to the prev page #}
        {% endif %}

        {% for pg in products.paginator.page_range %}
                    <a href="?page = {{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}  active {% endif %}"> {{pg}} </a>{% endfor %}
        {%if products.has_next %} {# whether the next page exists #}
            <a href="?page={{products.next_page_number}}"> > </a> {# link to the next page #}
        {% endif %}
    </div>
</div>


{% endblock %}

store/templates/footer.html
{% load static %}

<div class="footer fixed-bottom my-footer">
    <p class="text-center"> &copy: XYZ Supermarket</p>
</div>

store/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'storeapp:AllProdCat' %}" >
            <img src ="{% static 'img/logo.png' %}" alt="logimage" width="100px" height="100px"> </a>
    </center>
</header>

store/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Hello
</body>
</html>

store/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item ">
          <a class="nav-link " aria-current="page" href="/store">Home</a>
        </li>


        <li class="nav-item dropdown {% if Store in request.path %} active {% endif %} ">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Store
          </a>
          <ul class="dropdown-menu">
             <li><a class="dropdown-item" href="{% url 'storeapp:AllProdCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_details' %}"> <img src="{% static 'img/cart_icon.png' %} " width="15px" height="15px">({{item_count}}) </a>
        </li>
        {% endif %}
      </ul>

    </div>
    <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="post">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched">
        <button class="btn btn-outline-success" type="submit"><img src="{% static 'img/search_icon.png' %} " width="15px" height="15px"></button>
      </form>
  </div>
</nav>

store/templates/product.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}

        {{ product.description | truncatewords:155 }}

{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }}
    {% else %}
        XYZ Supermarket
    {% endif %}
{% endblock %}
{% block content %}

<div class="row my_prod_row">
    <div class="mx_auto">
        <p>
            <a href="{% url 'storeapp:AllProdCat' %}">Home</a>
            <a href="{{ product.category.get_url}}">{{product.category}}</a> | {{product.name}}
        </p>
    </div>
</div>

<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width: 18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title">{{Product.home}}</h1>
            <p> ${{product.price}} </p>
            <p class="my_prod_title">Product Description</p>
            <p class="text-justify my_prod_text"> {{product.description}}</p>
            {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id%}" >Add to Cart</a>
            {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

store/templates/search.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}

        We have variety of product

{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center mysearch_text">Search results for : <b>"{{query}}"</b></p>
</div>



<div class="container">
            <div class="my_bottom_margin ">
                {% for product in products %}
                <div class="col-md-12">

                    <div class="card text-center " style="min-width:10rem">

                    <a href="{{product.get_url}}"> <img class="card-img-top my_image img_category" src="{{product.image.url}}" alt="{{product.name}}"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
                </div>
                    {% endfor %}
                    </div>
                {% for product in products %}
                {% empty %}
                <div class="row mx-auto">
                    <p class="text-center my_search_text"> 0 results found</p>
                </div>
                {% endfor %}
            </div>

</div>

{% endblock %}

store/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
Hello World
</body>
</html>